version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/domainr/epp
    docker:
      - image: domainr/ci:swan
    steps:
      # Get Code
      # Workaround for {{ .Environment.VAR_NAME }} not reading custom environment keys
      - run:
          name: Cache Key Workaround for Environment
          command: |
            echo "$CACHE_VERSION" > ~/CACHE_VERSION
            echo "$GOLANG_VERSION" > ~/GOLANG_VERSION
      # Checkout Code
      - checkout
      - run: git branch --set-upstream-to=origin/$CIRCLE_BRANCH $CIRCLE_BRANCH
      # Build
      - run: go get -v -u -t -d ./...
      - run: test $(git rev-parse HEAD) = $CIRCLE_SHA1
      - run: go build -v -i
      - run: go test -v -i -race ./...
      # Test
      - run: mkdir -p /tmp/test-results
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report < /tmp/test-results/go-test.log > /tmp/test-results/go-test-report.xml" EXIT
            go test -v -race ./... | tee /tmp/test-results/go-test.log
      # Report
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: results

workflows:
  version: 2
  commit_workflow:
    jobs:
      - build
